---
abstract: 'Test Rinci metadata'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires:
  Capture::Tiny: 0
  Module::Build: 0.3601
  Test::More: 0.88
  Test::Script: 1.05
  blib: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.132140'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Rinci
requires:
  Log::Any::App: 0
  Perinci::Access::Perl: 0.36
  Perinci::Sub::GetArgs::Argv: 0.21
  Test::More: 0.98
  perl: 5.010001
resources:
  homepage: http://metacpan.org/release/Test-Rinci
  repository: http://github.com/sharyanto/perl-Test-Rinci
version: 0.03
